# Generated by Django 3.2 on 2021-04-26 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=20)),
                ('h_sex', models.BooleanField(default=False)),
                ('h_comment', models.CharField(max_length=128)),
                ('h_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.bookinfo')),
            ],
        ),
    ]
