# Generated by Django 3.2 on 2021-04-29 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_title', models.CharField(max_length=20)),
                ('b_pub_date', models.DateField()),
                ('b_read', models.IntegerField(default=0)),
                ('b_comment', models.IntegerField(default=0)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HeroInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=20)),
                ('h_sex', models.BooleanField(default=False)),
                ('h_comment', models.CharField(max_length=200)),
                ('is_delete', models.BooleanField(default=False)),
                ('h_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AreaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.CharField(max_length=20)),
                ('p', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.areainfo')),
            ],
        ),
    ]
