# Generated by Django 3.2 on 2021-05-06 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_placeinfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinfo',
            table='bookinfo',
        ),
        migrations.DeleteModel(
            name='AreaInfo',
        ),
    ]
